[window]
title = "Weevil"
width = 1_920
height = 1_080
resizable = false
fullscreen = false

[general]
assets = "/home/nelson/Development/Weevil/assets"
modules_dir = "/home/nelson/Development/Weevil/modules"
